"""Update categories scheme

Revision ID: 3a84ae2bf8eb
Revises:
Create Date: 2025-11-19 12:58:18.165599

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a84ae2bf8eb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_unique_constraint("uq_user_category", "categories", ["user_id", "name"])
    op.alter_column("expenses", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "expenses",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("expenses", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("uq_user_category", "categories", type_="unique")
    op.drop_column("categories", "user_id")
    # ### end Alembic commands ###
